// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IMDataProto.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class IMData_InitData;
@class IMData_MsgData;
@class IMData_MsgData_FromUser;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ImdataProtoRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ImdataProtoRoot : GPBRootObject
@end

#pragma mark - IMData

typedef GPB_ENUM(IMData_FieldNumber) {
  IMData_FieldNumber_Id_p = 1,
  IMData_FieldNumber_Type = 2,
  IMData_FieldNumber_InitData = 3,
  IMData_FieldNumber_MsgData = 4,
  IMData_FieldNumber_Timestamp = 5,
  IMData_FieldNumber_Expand = 6,
};

@interface IMData : GPBMessage

/** 消息ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/** 消息类型 4=心跳 1=初始化参数 2=消息 3=应答 */
@property(nonatomic, readwrite) int32_t type;

/** 初始化参数 type=2不为空 */
@property(nonatomic, readwrite, strong, null_resettable) IMData_InitData *initData;
/** Test to see if @c initData has been set. */
@property(nonatomic, readwrite) BOOL hasInitData;
- (IMData_InitData *)initData GPB_METHOD_FAMILY_NONE;

/** 消息数据 type=2不为空 */
@property(nonatomic, readwrite, strong, null_resettable) IMData_MsgData *msgData;
/** Test to see if @c msgData has been set. */
@property(nonatomic, readwrite) BOOL hasMsgData;

/** 时间戳 */
@property(nonatomic, readwrite) int64_t timestamp;

/** 拓展字段（方便后期拓展） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *expand;
/** The number of items in @c expand without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger expand_Count;

@end

#pragma mark - IMData_InitData

typedef GPB_ENUM(IMData_InitData_FieldNumber) {
  IMData_InitData_FieldNumber_HeartbeatMs = 1,
  IMData_InitData_FieldNumber_TimeoutMs = 2,
  IMData_InitData_FieldNumber_ReconnectMaxNum = 3,
  IMData_InitData_FieldNumber_ReconnectMs = 4,
  IMData_InitData_FieldNumber_AllowAccess = 5,
  IMData_InitData_FieldNumber_Expand = 6,
};

/**
 * 初始化数据
 **/
@interface IMData_InitData : GPBMessage

/** 心跳时间（毫秒） */
@property(nonatomic, readwrite) int32_t heartbeatMs;

/** 超时断开时间（毫秒） */
@property(nonatomic, readwrite) int32_t timeoutMs;

/** 重连最大次数 */
@property(nonatomic, readwrite) int32_t reconnectMaxNum;

/** 重连间隔时间 */
@property(nonatomic, readwrite) int32_t reconnectMs;

/** 是否允许访问 */
@property(nonatomic, readwrite) BOOL allowAccess;

/** 拓展字段（方便后期拓展） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *expand;
/** The number of items in @c expand without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger expand_Count;

@end

#pragma mark - IMData_MsgData

typedef GPB_ENUM(IMData_MsgData_FieldNumber) {
  IMData_MsgData_FieldNumber_Id_p = 1,
  IMData_MsgData_FieldNumber_SysId = 2,
  IMData_MsgData_FieldNumber_SessionId = 3,
  IMData_MsgData_FieldNumber_SType = 4,
  IMData_MsgData_FieldNumber_EmpSid = 5,
  IMData_MsgData_FieldNumber_FromUser = 6,
  IMData_MsgData_FieldNumber_ToUserId = 7,
  IMData_MsgData_FieldNumber_MsgType = 8,
  IMData_MsgData_FieldNumber_CustomType = 9,
  IMData_MsgData_FieldNumber_MsgBody = 10,
  IMData_MsgData_FieldNumber_SendTime = 11,
  IMData_MsgData_FieldNumber_Expand = 12,
};

/**
 * 消息数据
 **/
@interface IMData_MsgData : GPBMessage

/** 主键 */
@property(nonatomic, readwrite) int64_t id_p;

/** 系统平台ID */
@property(nonatomic, readwrite) int64_t sysId;

/** 会话ID */
@property(nonatomic, readwrite) int64_t sessionId;

/** 会话类型:1=用户点对点 2=客服点对点 */
@property(nonatomic, readwrite) int32_t sType;

/** 客服会话ID */
@property(nonatomic, readwrite) int64_t empSid;

/** 发送方用户信息 */
@property(nonatomic, readwrite, strong, null_resettable) IMData_MsgData_FromUser *fromUser;
/** Test to see if @c fromUser has been set. */
@property(nonatomic, readwrite) BOOL hasFromUser;

/** 接收方用户ID */
@property(nonatomic, readwrite) int64_t toUserId;

/** 消息类型：text=文本 audio=音频 file=文件 position=定位 custom=自定义 system=系统消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgType;

/** 自定义消息类型 msgType = custom 不为空 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *customType;

/** 消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgBody;

/** 发送时间 */
@property(nonatomic, readwrite) int64_t sendTime;

/** 拓展字段（方便后期拓展） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *expand;
/** The number of items in @c expand without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger expand_Count;

@end

#pragma mark - IMData_MsgData_FromUser

typedef GPB_ENUM(IMData_MsgData_FromUser_FieldNumber) {
  IMData_MsgData_FromUser_FieldNumber_Id_p = 1,
  IMData_MsgData_FromUser_FieldNumber_SysId = 2,
  IMData_MsgData_FromUser_FieldNumber_BusUserId = 3,
  IMData_MsgData_FromUser_FieldNumber_NickName = 4,
  IMData_MsgData_FromUser_FieldNumber_HeadImg = 5,
  IMData_MsgData_FromUser_FieldNumber_Expand = 6,
};

/**
 * 发送方用户信息
 **/
@interface IMData_MsgData_FromUser : GPBMessage

/** 主键 */
@property(nonatomic, readwrite) int64_t id_p;

/** 系统平台ID */
@property(nonatomic, readwrite) int64_t sysId;

/** 业务系统用户ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *busUserId;

/** 昵称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *nickName;

/** 用户头像url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *headImg;

/** 拓展字段（方便后期拓展） */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *expand;
/** The number of items in @c expand without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger expand_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
